In [27]:
import pandas as pd
df = pd.read_csv("../data/raw/2026-10-22.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      126 non-null    int64
 1   name    126 non-null    str
 2   price   126 non-null    float64
 3   date    126 non-null    str
dtypes: float64(1), int64(1), str(2)
memory usage: 4.1 KB

In [28]:
df.head()

,id,name,price,date
0,4753925,MSI VGA GeForce RTX 3050 VENTUS 2X E OC 6 GB,269.0,2026-10-22
1,4796691,PNY VGA Nvidia RTX PRO 6000 Blackwell 96 GB,19999.0,2026-10-22
2,5339936,Asus VGA GeForce RTX 5090 ROG Astral Edition 2...,7999.0,2026-10-22
3,4791908,MSI VGA GeForce RTX RTX 5060 SHADOW 2X OC 8 GB,429.0,2026-10-22
4,4810066,Sapphire VGA Radeon RX 9060 XT NITRO+ OC 16 GB,759.0,2026-10-22

In [29]:
df["name"] = df["name"].str.replace("VGA ", "")
df["brand"] = df["name"].str.split().str[0]

In [30]:
print(df["brand"])

0           MSI
1           PNY
2          Asus
3           MSI
4      Sapphire
         ...
121    Sapphire
122        Asus
123        Asus
124        Asus
125        Asus
Name: brand, Length: 126, dtype: object

In [31]:
df["brand"].value_counts()

brand
Gigabyte    38
Asus        24
MSI         19
PNY         19
Sapphire    13
Asrock       6
AMD          5
Intel        1
XFX          1
Name: count, dtype: int64

In [32]:
df[df["brand"] == "VGA"]

Empty DataFrame
Columns: [id, name, price, date, brand]
Index: []

In [ ]:
df["name"].str.contains("Radeon|AMD", case = False).sum()

np.int64(35)

In [ ]:
df["name"].str.contains("GeForce|Nvidia", case = False).sum()

np.int64(83)

In [ ]:
df["name"].str.contains("Intel|Arc", case = False).sum()

np.int64(3)

In [38]:
amd = df["name"].str.contains("Radeon|AMD", case = False)
nvidia = df["name"].str.contains("GeForce|Nvidia", case = False)
intel = df["name"].str.contains("Intel|Arc", case = False)
df[~(amd|nvidia|intel)]

          id                               name  price        date brand
64   4590023   PNY Quadro A400 Low Profile 4 GB  349.0  2026-10-22   PNY
99   4590031  PNY Quadro A1000 Low Profile 8 GB  799.0  2026-10-22   PNY
115  4042328   PNY Quadro T400 Low Profile 4 GB  199.0  2026-10-22   PNY
117  3494659            PNY Quadro P620 V2 2 GB  199.9  2026-10-22   PNY
118  2902818          PNY Quadro P620 2GB GDDR5  249.9  2026-10-22   PNY

In [39]:
df["name"].str.contains("GeForce|Nvidia|PNY", case = False).sum()
nvidia = df["name"].str.contains("GeForce|Nvidia|PNY", case = False)

In [40]:
df[~(amd|nvidia|intel)]

Empty DataFrame
Columns: [id, name, price, date, brand]
Index: []

In [41]:
amd.sum() + nvidia.sum() + intel.sum()

np.int64(126)

In [42]:
df.loc[amd, "gpu_maker"] = "AMD"
df.loc[nvidia, "gpu_maker"] = "NVIDIA"
df.loc[intel, "gpu_maker"] = "INTEL"

In [44]:
df["gpu_maker"].value_counts()

gpu_maker
NVIDIA    88
AMD       35
INTEL      3
Name: count, dtype: int64

In [46]:
df.head(10)

,id,name,price,date,brand,gpu_maker
0,4753925,MSI GeForce RTX 3050 VENTUS 2X E OC 6 GB,269.0,2026-10-22,MSI,NVIDIA
1,4796691,PNY Nvidia RTX PRO 6000 Blackwell 96 GB,19999.0,2026-10-22,PNY,NVIDIA
2,5339936,Asus GeForce RTX 5090 ROG Astral Edition 20 32 GB,7999.0,2026-10-22,Asus,NVIDIA
3,4791908,MSI GeForce RTX RTX 5060 SHADOW 2X OC 8 GB,429.0,2026-10-22,MSI,NVIDIA
4,4810066,Sapphire Radeon RX 9060 XT NITRO+ OC 16 GB,759.0,2026-10-22,Sapphire,AMD
5,4810090,Sapphire Radeon RX 9060 XT PULSE OC 16 GB,719.0,2026-10-22,Sapphire,AMD
6,4699440,Sapphire Radeon RX 9070 XT NITRO+ OC 16 GB,1199.0,2026-10-22,Sapphire,AMD
7,4820118,Gigabyte GeForce GT 710D3 2 GB,69.9,2026-10-22,Gigabyte,NVIDIA
8,5337283,Asus GeForce RTX 5060 Dual OC Advanced 8 GB,599.0,2026-10-22,Asus,NVIDIA
9,5164052,Asus Radeon RX 9070 GRE PRIME OC 12 GB,749.0,2026-10-22,Asus,AMD