In [11]:
import pandas as pd
df = pd.read_csv("../data/raw/2026-10-22.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      126 non-null    int64
 1   name    126 non-null    str
 2   price   126 non-null    float64
 3   date    126 non-null    str
dtypes: float64(1), int64(1), str(2)
memory usage: 4.1 KB

In [12]:
df.head()

,id,name,price,date
0,4753925,MSI VGA GeForce RTX 3050 VENTUS 2X E OC 6 GB,269.0,2026-10-22
1,4796691,PNY VGA Nvidia RTX PRO 6000 Blackwell 96 GB,19999.0,2026-10-22
2,5339936,Asus VGA GeForce RTX 5090 ROG Astral Edition 2...,7999.0,2026-10-22
3,4791908,MSI VGA GeForce RTX RTX 5060 SHADOW 2X OC 8 GB,429.0,2026-10-22
4,4810066,Sapphire VGA Radeon RX 9060 XT NITRO+ OC 16 GB,759.0,2026-10-22

In [13]:
df["name"] = df["name"].str.replace("VGA ", "")
df["brand"] = df["name"].str.split().str[0]

In [14]:
print(df["brand"])

0           MSI
1           PNY
2          Asus
3           MSI
4      Sapphire
         ...
121    Sapphire
122        Asus
123        Asus
124        Asus
125        Asus
Name: brand, Length: 126, dtype: object

In [15]:
df["brand"].value_counts()

brand
Gigabyte    38
Asus        24
MSI         19
PNY         19
Sapphire    13
Asrock       6
AMD          5
Intel        1
XFX          1
Name: count, dtype: int64

In [16]:
df[df["brand"] == "VGA"]

Empty DataFrame
Columns: [id, name, price, date, brand]
Index: []